### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by msutkowski** [rtk-incubator/rtk-query#35]
- [x] passable API docs
- [x] basic usage examples
- [x] examples of using an alternate query implementation (say, `axios` with some interceptors, and maybe a GraphQL fetching example if that's a doable thing?)
- [x] a bit of discussion on lib/API naming

_Originally posted by @markerikson in https://github.com/rtk-incubator/rtk-query/issues/15#issuecomment-724890932_

- [x] Class component example
- [x] Vanilla JS example
- [x] Examples using other api types with a custom baseQuery
  - [x] graphql
  - [ ] rpc calls using websockets or grpc
- [x] Pre-seeding the cache by dispatching a non-subscribing queryAction from a parent component
   - Covered in `Prefetching`

**Comment by markerikson** [comment]
Where are the alternate query impl examples at?

**Comment by phryneas** [comment]
Funny enough, graphql didn't need another query implementation :D

**Comment by msutkowski** [comment]
https://rtk-query-docs.netlify.app/examples/react-with-graphql
https://rtk-query-docs.netlify.app/api/createApi#transforming-the-data-returned-by-an-endpoint-before-caching

And I'll be adding that to the `baseQuery` section of `createApi`, as well as adding examples to `Queries`

**Comment by markerikson** [comment]
niiiice!

**Comment by msutkowski** [comment]
@markerikson Thanks! I have a mental note to go through and do a cleanup pass of all sandboxes before we do a public alpha. I was looking through the CSB options, and it appears we can focus on the file like you said, as well as highlight text, etc etc. I'll need to experiment some there. The other feedback I got was:  

> ya, csb just needs to make their embed thing more obvious that you can pull the code out when it's narrow

**Comment by markerikson** [comment]
Do we have an example of using `extraReducers` to do some additional handling of a query-dispatched action, like using `createEntityAdapter` to store a second copy of the values?

**Comment by msutkowski** [comment]
Not yet - but I'll be adding that. @phryneas is opening an issue regarding
callbacks on Endpoints like `onSuccess`, `onError`, `onStart` that may
impact that :)

**Comment by komarov-sergey** [comment]
Thanks for your work!
I'm really looking forward to an example with gRPC.

**Comment by phryneas** [comment]
@komarov-sergey do you know of any (relatively simple) public grpc api we could use for an example? That was the prime blocker for that.

**Comment by komarov-sergey** [comment]
@phryneas I dont know public grpc api, but you can just give an example of server.js and configs for run it locally. Here is my repo with todo list (RTK + gRPC + server) https://github.com/komarov-sergey/react-gRPC
